### ISSUE TITLE
Email issues

### ISSUE THREAD

**Issue by thomasdupas** [Bouni/blog.bouni.de#1]
Hi bouni,
Creating ticket here, just so you’re aware that the mail server/address listed on the blog for owee.de doesn’t seem to allow mails.
For bounces both via my own mail server as via gmail.

Could be intentional of course, so just a heads up in case it isn’t

**Comment by Bouni** [comment]
Hey, thanks for pointing this out!
Can you give a bit more specific information what email address you've tried to send from or what he error said you got?
Just tried to send an email from my company email address and that one went through without any problems.

**Comment by thomasdupas** [comment]
Gmail got blacklisted (which sounds a bit weird)
“ 554 5.7.1 Service unavailable; Client host [209.85.167.53] blocked using new.spam.dnsbl.sorbs.net; Currently Sending Spam See: http://www.sorbs.net/lookup.shtml?209.85.167.53 "

And from my own server I got a
“ host mail.owee.de[188.34.154.202] said: 450 4.7.1 <mail-out.dupas.be>: Helo command rejected: Host not found (in reply to RCPT TO command)”
(Even though that PTR record should exist)

So tried from thomas at dupas . be and thomas . dupas at gmail . com

**Comment by Bouni** [comment]
Hi,

indeed, that gmail mauilserver is blacklisted and my mailserver does automatically revert mails comming from blacklisted mailservers.
Does your mail address on your domain also facilitate the gmail mailservers?

Otherwise that should work in my opinion as it not listed on any blacklist (https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3adupas.be&run=toolpage)

Edit: I've just sent you an email to thomas at dupas . be

**Comment by thomasdupas** [comment]
I've received your mail and replied, after greylisting it seems to have been accepted by your server. So should see my reply if all went well.

**Comment by samuelb** [comment]
Hi Thomas

I run the mailserver Bouni is using.

I put now googles mailserver onto the whilelist. The listing in sorbs RBL shouldn't be the problem anymore.

Regarding the rejection of your mailserver. In the time between 20 to 26 of May your server got rejected because the reverse lookup of the IP address wasn't possible. If there was a PTR set up, than, for whatever reason, my server wasn't able to resolve it. On May 26 11:26:29 the PRT lookup was possible and the mail when trough (after greylisting).

**Comment by Bouni** [comment]
I got the mails, so this is resolved
